services:
  interruptor-landing:
    build:
      context: ../landingpage
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true
